[theme]
base = "dark"
primaryColor = "#3987e5"
backgroundColor = "#0b1426"
secondaryBackgroundColor = "#13203a"
textColor = "#e6edf7"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
